import { expect, test, type Page } from '@playwright/test'

export async function setSlider(page: Page, label: string, value: number) {
  const slider = page.getByRole('slider', { name: label, exact: true })
  await slider.fill(String(value))
}

test('day/time state, duplicate markers, details and appearance controls', async ({ page }) => {
  await page.goto('/#experience')
  await expect(page.getByTestId('active-count')).toHaveText('27 ACTIVE ACTIVITIES')
  await setSlider(page, 'Day', 6) // Saturday in SUN-first UI
  await setSlider(page, 'Time', 1140)
  await expect(page.getByTestId('active-count')).toHaveText('9 ACTIVE ACTIVITIES')
  await expect(page.locator('#experience [data-place=P14]')).toHaveAttribute('data-active', 'true')
  await page.locator('#experience [data-place=P14]').focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toContainText('ถนนคนเดิน')
  await expect(page.getByRole('dialog')).toContainText('16:00–23:00')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await setSlider(page, 'Time', 1380)
  await expect(page.locator('#experience [data-place=P14]')).toHaveAttribute('data-active', 'false')
  await expect(page.getByTestId('active-count')).toHaveText('0 ACTIVE ACTIVITIES')
  await setSlider(page, 'Day', 1)
  await setSlider(page, 'Time', 720)
  await expect(page.locator('#experience [data-place=P20][data-active=true]')).toHaveCount(7)
  await expect(page.getByTestId('active-count')).toHaveText('27 ACTIVE ACTIVITIES')
  await page.getByRole('button', { name: 'Night mode' }).click()
  await expect(page.locator('main')).toHaveAttribute('data-theme', 'night')
  await expect(page.getByTestId('active-count')).toHaveText('27 ACTIVE ACTIVITIES')
  await page.getByRole('button', { name: 'Show roads' }).click()
  await expect(page.locator('#experience .base-roads')).toHaveCSS('opacity', '0')
  await expect(page.locator('#experience [data-place=P14]')).toBeVisible()
  await page.getByRole('button', { name: 'REAL TIME' }).click()
  await expect(page.getByRole('button', { name: 'REAL TIME' })).toHaveAttribute('aria-pressed', 'true')
  await setSlider(page, 'Time', 1440)
  await expect(page.getByRole('button', { name: 'REAL TIME' })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByTestId('active-count')).toHaveText('0 ACTIVE ACTIVITIES')
})

test('interactive hero, unified icon controls, persistent marker selection and method reveal', async ({page}) => {
  await page.goto('/')
  await expect(page.locator('.hero .activity-map')).toBeVisible()
  await expect(page.locator('.hero-copy h1')).toContainText('The Echoes of Wua-lai')
  await expect(page.locator('.hero .map-marker')).toHaveCount(60)
  await expect(page.locator('.hero [data-category="Crafthouse"] rect')).toHaveCount(0)
  await page.getByRole('button', {name:'Enter the active map'}).click()
  await expect(page.locator('#experience')).toBeInViewport()
  await expect(page.locator('.actions .control-icon')).toHaveCount(4)
  const marker = page.locator('#experience [data-place=P20]').first()
  await marker.hover()
  await expect(marker).toHaveAttribute('data-hovered', 'true')
  await expect(page.locator('#experience .map-marker[data-dimmed=true]').first()).toBeVisible()
  await marker.click()
  await page.locator('.controls').hover()
  await expect(marker).toHaveAttribute('data-selected', 'true')
  await expect(page.getByRole('dialog')).toContainText('Crafthouse')
  await expect(page.getByRole('dialog')).toContainText(/Active|Inactive/)
  await expect(page.locator('#experience .map-marker[data-dimmed=true]').first()).toBeVisible()
  await page.getByRole('button', {name:'View how it works'}).click()
  await expect(page.locator('.method')).toHaveAttribute('data-revealed', 'true')
  await expect(page.locator('.method')).toBeInViewport()
})
