import { expect, test } from '@playwright/test'

test('realtime entry and navigation preserve map state and history', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-28T05:00:00Z'))
  await page.goto('/')
  await expect(page.locator('.hero')).toHaveCount(0)
  await expect(page.getByRole('button', {name:'REAL TIME',exact:true})).toHaveAttribute('aria-pressed','true')
  await expect(page.getByRole('slider',{name:'Time',exact:true})).toHaveValue('720')
  await expect(page.getByRole('button',{name:'Play soundscape',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Saturday',exact:true}).click()
  await page.getByRole('slider',{name:'Time',exact:true}).fill('1140')
  await expect(page.getByTestId('active-count')).toHaveText('9 ACTIVE ACTIVITIES')
  await page.getByRole('link',{name:'About Wua-lai',exact:true}).click()
  await expect(page.getByRole('region',{name:'About Wua-lai',exact:true})).toBeVisible()
  await page.getByRole('link',{name:'Method',exact:true}).click()
  await page.goBack()
  await expect(page).toHaveURL(/#about$/)
  await page.getByRole('link',{name:'Soundscape',exact:true}).click()
  await expect(page.getByTestId('active-count')).toHaveText('9 ACTIVE ACTIVITIES')
  await expect(page.getByRole('button',{name:'Saturday',exact:true})).toHaveAttribute('aria-pressed','true')
})

test('about carousel and independent method disclosure work with keyboard', async ({page}) => {
  await page.goto('/#about')
  const carousel=page.getByRole('region',{name:'Wua-lai photographs'})
  await carousel.focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.locator('.about-slide[data-current=true]')).toContainText('Silversmithing')
  await page.keyboard.press('End')
  await expect(page.locator('.about-slide[data-current=true]')).toContainText('A destination shaped by local culture')
  await expect.poll(async()=>{
    const track=await carousel.boundingBox()
    const slide=await page.locator('.about-slide[data-current=true]').boundingBox()
    return Math.abs((track!.x+track!.width/2)-(slide!.x+slide!.width/2))
  }).toBeLessThan(3)
  await page.keyboard.press('ArrowLeft')
  await expect(page.locator('.about-slide[data-current=true]')).toContainText('Street life')
  await page.getByRole('link',{name:'Method',exact:true}).click()
  await expect(page.locator('.method button[aria-expanded=false]')).toHaveCount(9)
  await page.getByRole('button',{name:'CATEGORY WEIGHT',exact:true}).click()
  await expect(page.getByRole('table',{name:'Category weights'})).toBeVisible()
  await page.getByRole('button',{name:'SOUND INTENSITY',exact:true}).click()
  await expect(page.getByRole('table',{name:'Sound intensity examples'})).toBeVisible()
  await expect(page.getByRole('table',{name:'Category weights'})).toBeVisible()
  await page.getByRole('button',{name:'CATEGORY WEIGHT',exact:true}).click()
  await expect(page.getByRole('table',{name:'Category weights'})).not.toBeVisible()
})
